### ISSUE TITLE
Date and time pattern strings are missing in docs

### ISSUE THREAD

**Issue by this** [wso2-extensions/siddhi-execution-time#32]
**Description:**
Docs on [`dateFormat`](https://wso2-extensions.github.io/siddhi-execution-time/api/4.0.10/#dateformat-function) and other related functions do not have reference on supported _date and time pattern strings_.

`dateFormat` function supports _date and time pattern strings_ that are supported by the [`SimpleDateFormat` Java class](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html) for `date.target.format` parameter.

**Affected Product Version:**
v4.0.0>

**Comment by niveathika** [comment]
The above issue is fixed by https://github.com/wso2-extensions/siddhi-execution-time/pull/35

**Comment by this** [comment]
Closing as per above comment.
