### ISSUE TITLE
Conflict of documentation and the code of time:dateDiff()

### ISSUE THREAD

**Issue by BuddhiWathsala** [wso2-extensions/siddhi-execution-time#53]
**Description:**
In the [documentation](https://siddhi-io.github.io/siddhi-execution-time/api/5.0.3/#datediff-function) of `time:dateDiff` the order of the arguments describe as follow.

```sql
<INT> time:dateDiff(<STRING> date.value1, <STRING> date.format1, <STRING> date.value2, <STRING> date.format2)timestamp.in.milliseconds2)
```

But in the code level, it coded as follow.

```
Accept Type(s) for dateDiff(dateValue1,dateValue2,dateFormat1,dateFormat2):
         dateValue1 : STRING
         dateValue2 : STRING
         dateFormat1 : STRING
         dateFormat2 : STRING
```

**Suggested Labels:**
Documentation improvement

**Affected Product Version:**
v5.0.3

**Comment by mohanvive** [comment]
Fixed in https://github.com/siddhi-io/siddhi-execution-time/pull/54 ...
