### ISSUE TITLE
Override default UTC Timestamp format

### ISSUE THREAD

**Issue by ashmeet-kandhari** [wso2-extensions/siddhi-execution-time#61]
**Description:**
Right now the default UTC timestamp is `EXTENSION_TIME_UTC_TIMESTAMP_FORMAT  = "yyyy-MM-dd HH:mm:ss"`.
We should have an argument which supports other timestamp formats as well for `time:utcTimestamp()`

**Comment by dnwick** [comment]
Fixed in https://github.com/siddhi-io/siddhi-execution-time/pull/62
